application: able-inn-471
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.application

- url: /dist/css
  static_dir: dist/css

- url: /dist/js
  static_dir: dist/js

- url: /dist/fonts
  static_dir: dist/fonts

libraries:
- name: MySQLdb
  version: "latest"

- name: jinja2
  version: "latest"
