application: able-inn-471
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.application

- url: /static
  static_dir: static

libraries:
- name: MySQLdb
  version: "latest"

- name: jinja2
  version: "latest"
