application: fortunatepunt
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.application

- url: /css
  static_dir: static/css

- url: /fonts
  static_dir: static/fonts

- url: /js
  static_dir: static/js


libraries:
- name: MySQLdb
  version: "latest"

- name: jinja2
  version: "latest"
